= Chapter 5 프로그래밍 문제 및 퀴즈 정의

=== link:https://math.hws.edu/javanotes/c5/exercises.html[Programing Exercise For Chapter 5]

---

==  Chapter 5 Quiz

* Question 2: Explain carefully what null means in Java, +
and why this special value is necessary.

.Answer
[%collapsible%open]
====
자바는 변수의 선언만 하고 정의내리지 않을 수 있습니다.

따라서 선언만 하고 어떠한 값을 갖고 있지 않는 상태가 가능 합니다.

그렇기에 이런 상태를 나타낼때 null을 사용 합니다.
====

* Question 3: What is a constructor? +
What is the purpose of a constructor in a class?

.Answer
[%collapsible%open]
====
생성자는 객체를 사용하기 위한 공간을 할당 시켜

인스턴스화 시킵니다.

====

* Question 5: What is meant by the terms instance variable and instance method?

.Answer
[%collapsible%open]
====
instance variable 과 method는 객체에 속한 것들을 의미합니다.

이는 쉽게 말하면 non - static 을 의미합니다.

static의 경우에는 객체에 포함되지 않고 클래스에 포함되기 때문에

instance에 속하지 않습니다.
====

* Question 11: What is an abstract class, and how can you recognize an abstract class in Java?

.Answer
[%collapsible%open]
====
추상 클래스는 implementation 을 갖고 있을 수도 있고 없을 수도 있으며

기능을 명시해놓은 추상 메서드를 갖고 있는 클래스를 의미합니다.

따라서 추상클래스는 new를 통해서 생성 할 수 없으며

abstract 키워드를 통해서 표현합니다.


====

* Question 12: What is this?

.Answer
[%collapsible%open]
====
this는 메서드 안에서 사용됩니다.

메서드는 객체.메서드의 꼴로 call되기 떄문에

this 는 메서드를 콜하는 객체를 지칭합니다.

====

* Question 15: Explain why it can never make sense to test "if (obj.equals(null))".

.Answer
[%collapsible%open]
====
null은 선언만 해놓고 정의하지 않은 상태를 의미합니다.

따라서 어떠한 값이나 어떠한 포인터도 가지지 않고 있으므로

만약 obj가 null이라면 애초에 equals를 부를 수 없습니다.
====






